export const FETCH_ORDERS_IN_PROGRESS = 'FETCH_ORDERS_IN_PROGRESS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_ORDER_IN_PROGRESS = 'FETCH_ORDER_IN_PROGRESS';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const CREATE_ORDER_IN_PROGRESS = 'CREATE_ORDER_IN_PROGRESS';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const RESET_NEW_ORDER = 'RESET_NEW_ORDER';

export const UPDATE_ORDER_IN_PROGRESS = 'UPDATE_ORDER_IN_PROGRESS';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE';

export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';
export const DELETE_ORDER_IN_PROGRESS = 'DELETE_ORDERS_IN_PROGRESS';

export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';
export const UPDATE_ORDER_STATUS_IN_PROGRESS = 'UPDATE_ORDER_STATUS_IN_PROGRESS';

export const PREPARE_FORM = 'PREPARE_FORM';


